services:
  demo-api:
    image: nginxdemos/hello:latest
    deploy:
      replicas: 1
    networks:
      - internal
    labels:
      app: demo-api

  swarm-refresher:
    image: yourusername/swarm-refresher:latest
    deploy:
      replicas: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTH_TOKEN=changeme-super-secret
    networks:
      - internal
    ports:
      - "8080:8080"

networks:
  internal:
    driver: overlay
