global:
  scrape_interval:     15s
  evaluation_interval: 15s
  
  - job_name: 'swarmctl'
    metrics_path: /metrics
    bearer_token: ${SWARMCTL_TOKEN}
    dns_sd_configs:
      - names:
          - 'tasks.swarmctl_server'
        type: 'A'
        port: 9000