name: ci
on:
  pull_request:
    paths: &code
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "mise.toml"
      - "mise.lock"
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/ci.yaml"
  push:
    branches-ignore:
      - "main"
    paths: *code

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Lint
        run: mise run lint

      - name: Vet
        run: mise run vet

      - name: Test
        run: mise run test-race

      - name: Build
        run: mise run build
